spring:
  flyway:
    enabled: true # Flyway ???
    # ?????? ?? ?? ?? (???)
    locations: classpath:db/migration

  datasource:
    url: jdbc:mysql://localhost:3306/spring_db?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA ? Hibernate ??
  jpa:
    hibernate:
      # ddl-auto: ?????? ?? ? ???(???) ?? ??
      # none: ?? ??? ?? ?? (?? ?? ??)
      # create: ?? ??? ?? ? ?? ??
      # update: ??? ??? ??
      ddl-auto: validate
    properties:
      hibernate:
        # MySQL 8 ??? ?? Dialect(??) ??
        dialect: org.hibernate.dialect.MySQL8Dialect

logging:
  level:
    # Hibernate? ???? SQL ??? DEBUG ??? ??? ??
    org.hibernate.SQL: DEBUG

# ?? ? ?? ??
server:
  port: 8082